version: '2'
services:
  eurekaserver:
    image: spmia-eurekasvr:chapter4
    ports:
      - "8761:8761"

  configserver:
    image: spmia-confsvr:chapter4
    ports:
      - "8888:8888"
    environment:
       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
       EUREKASERVER_PORT: "8761"
    links:
      - eurekaserver

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB: "eagle_eye_local"
    volumes:
      - ~/DevTools/postgres-data:/var/lib/postgresql/data

  licensing-service:
      image: spmia-licensing-service:chapter4
      ports:
        - "8080:8080"
      environment:
        PROFILE: default
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        CONFIGSERVER_PORT: "8888"
        DATABASESERVER_PORT: "5432"
      links:
        - eurekaserver
        - configserver
        - database

  organization-service:
      image: spmia-organization-service:chapter4
      ports:
        - "8081:8081"
      environment:
        PROFILE: default
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        CONFIGSERVER_PORT: "8888"
        DATABASESERVER_PORT: "5432"
      links:
        - eurekaserver
        - configserver
        - database

  organization-service-2:
      image: spmia-organization-service:chapter4
      ports:
        - "8082:8081"
      environment:
        PROFILE: default
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        CONFIGSERVER_PORT: "8888"
        DATABASESERVER_PORT: "5432"
      links:
        - eurekaserver
        - configserver
        - database

  organization-service-3:
      image: spmia-organization-service:chapter4
      ports:
        - "8083:8081"
      environment:
        PROFILE: default
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        CONFIGSERVER_PORT: "8888"
        DATABASESERVER_PORT: "5432"
      links:
        - eurekaserver
        - configserver
        - database
