server:
  port: 8888

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hunter1110/config-repo/
          searchPaths: '{application}'
